<?php
$this->headScript()->appendFile('/min/f=/assets/js/dropzone.js');
$this->headScript()->appendFile('/min/f=/assets/js/bootstrap-progressbar.js');
$this->headScript ()->appendFile ( '/js/funix/loadData.js' );
$this->headScript ()->appendFile ( '/min/f=/tp/v1/js/user/profile/edit.js?01' );
$this->headLink()->appendStylesheet('/css/dropzone.css');
$user = $this->user;
$form = $this->form;
?>
<div class="container">
    <!-- ngIf: !User.hasWebRTC -->
    <div check-time-zone=""></div>

    <div class="alerts ng-scope">
<!--        <div class="center alert flash-message topAlert ng-scope alert-success cookie-alert">-->
<!--            <a class="close" data-dismiss="alert">×</a>-->
<!--            <span class="ng-binding"></span>-->
<!--            <span>-->
<!--                <span class="ng-scope">Make sure you're properly set up!  Please </span>-->
<!--                <a href="/session?intro=true" target="_blank" class="ng-scope">try a test session</a>-->
<!--                <span class="ng-scope"> and </span>-->
<!--                <a href="#" class="ng-scope">set up billing info</a>-->
<!--                <span class="ng-scope">.</span>-->
<!--            </span>-->
<!--            <a class="never-ask-again muted" href="#" style="padding-left:10px;text-decoration:underline;">-->
<!--                Never ask again-->
<!--            </a>-->
<!--        </div><!-- end ngRepeat: alert in Alert.alerts -->
    </div>

    <div class="row-fluid">
        <div class="span3">
            <div class="menu well">
                <ul class="nav">
                    <!-- - if current_user.is_mentor? -->
                    <!-- = nav_link "Codementor Monthly", users_long_term_mentorship_path -->
                    <li class="navHeader">
                        <i class="icon-cog"></i>
                        Chỉnh sửa
                    </li>
                    <li class="active"><a href="/profile/edit">Chỉnh sửa hồ sơ</a></li>
<!--                    <li><a href="/users/edit">Account Settings</a></li>-->
<!--                    <li><a href="/users/blocked_users">Blocked Users</a></li>-->
<!--                    <li><a href="/users/organization">Organization</a></li>-->
<!--                    <li class="navHeader">-->
<!--                        <i class="icon-credit-card"></i>-->
<!--                        Billing-->
<!--                    </li>-->
<!--                    <li><a href="/users/buy_credit">Buy Credit</a></li>-->
<!--                    <li><a href="/users/referral">Earn Free Credit</a></li>-->
<!--                    <li><a href="/users/payment_setting">Payment Method</a></li>-->
<!--                    <li><a href="/payments">Payment History</a></li>-->
                </ul>
            </div>
        </div>

        <div class="span9">
            <div class="well">
                <legend>
                    Hồ sơ của bạn
                </legend>
                <?php
                $form->setAttributes([
                    'class'=>'simple_form edit_user ng-pristine ng-valid'
                ]);
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formelement($form->get('fullName')->setAttributes(array(
                    'class'			=>	'string required input-xxlarge',
                    'autofocus'		=>	'autofocus',
                    'placeholder'	=>	'Tên...',
                ))->setValue($user->getFullName()));
                echo $this->formelementerrors($form->get('fullName'),[
                    'class'	=>	'text-error',
                    'id'    =>  'error_info'
                ]);
                echo '<label>Thành phố</label>';
                echo $this->formelement($form->get('cityId')->setAttributes(array(
                    'class' =>  'input-xxlarge',
                    'id'    =>  'cityId',
                ))->setValue($user->getCityId()));
                echo '<label>Quận/Huyện</label>';
                echo $this->formelement($form->get('districtId')->setAttributes(array(
                    'class' =>  'input-xxlarge',
                    'id'    =>  'districtId',
                ))->setValue($user->getDistrictId()));
                echo '<label class="string optional control-label">Address</label>';
                echo $this->formelement($form->get('address')->setAttributes(array(
                    'class' =>  'input-xxlarge',
                    'id'    =>  'address',
                )));
                if($user->getRole() == \User\Model\User::ROLE_MENTOR){
                    echo '<label class="string optional control-label">Giới thiệu</label>';
                    echo $this->formelement($form->get('description')->setAttributes(array(
                        'id'    =>  'description',
                    )));
                }
                ?>
                <profile-image img-src="<?=\Home\Service\Uri::getViewPath($user)?>" class="ng-isolate-scope">
                    <div>
                        <div id="update-wrapper" class="image-wrapper">
                            <div class="img-polaroid profile-photo-big img-loading ng-hide" ></div>
                            <div class="dz-image" id="div-profile-photo">
                                <img id="profile-photo" class="img-polaroid profile-photo-big" src="<?= \Home\Service\Uri::getViewPath($user)?>">
                            </div>
                            <div class="update-wrapper dz-default dz-message" >
                                <div class="update-icon"><i class="icon-camera"></i></div>
                                <div class="update-text"> Update Photo      </div>
                            </div>
                        </div>
                    </div>
                </profile-image>
                <p class="text-error hidden" id="error_img" style="margin-top:12px;">
                    We only accept alphanumeric characters, underscore, periods, dash, space and single quote.
                </p>
                <div id="preview-template" style="display: none;">
                    <div class="dz-preview dz-file-preview col-md-3 status-uploading">
                        <div class="item">
                            <div class="item-preview">
                                <div class="dz-image">
                                    <img data-dz-thumbnail="">
                                </div>
                            </div>
                            <div class="item-info">
                                <div class="dz-details">
                                    <div class="size">
                                        <div class="dz-size">
                                            <span data-dz-size=""></span>
                                        </div>
                                    </div>
                                    <div class="name fontsize-85">
                                        <div class="dz-filename">
                                            <span data-dz-name=""></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="progress progress-striped active" role="progressbar"
                                     aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                                    <div class="progress-bar progress-bar-success" style="width: 0%;"
                                         data-dz-uploadprogress></div>
                                </div>

                                <div class="dz-error-message">
                                    <span data-dz-errormessage=""></span>
                                </div>
                                <div class="dz-success-mark">
                                    <i class="fa-fa-check color-green"></i>
                                </div>
                                <div class="dz-error-mark">
                                    <i class="fa-fa-times color-red"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                <?php
                echo '<div>';
                echo $this->formelement($form->get('submit')->setAttributes(array(
                    'class' =>  'btn btn-primary submitBtn',

                )));
                echo '</div>';
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

</div>
<style>
    .menu .navHeader{background-color:#f8f9fa;line-height:40px;padding:0px 20px;color:#666}
</style>