<?php
$this->headLink()->appendStylesheet('\css\user\font-awesome.css');
$this->headLink()->appendStylesheet('\css\user\mentee-profile.css');
/** @var \User\Model\User $user */
$user = $this->user;
?>
<div class="menteeProfile ng-scope">
	<div class="form">
		<div class="personalInfoPart">
			<div class="customizeContainer">
				<div class="row-fluid">
					<div class="span8">
						<div class="row-fluid">
							<div class="span3">
								<center>
									<div class="profileImageWrapper">
										<a class="imageHover" href="/profile/edit">
											<img class="menteeImage img-circle img-rounded" src="https://www.gravatar.com/avatar/e396607e917deb8ab2306669cbede5f9?d=mm&amp;s=200">
											<div class="textOnHover">
												Update Photo
											</div>
										</a>
									</div>
								</center>
							</div>
							<div class="span9">
								<div class="nameBlock">
									<h1 class="menteeName ng-binding"><?=$user->getFullName()?$user->getFullName():$user->getUsername()?></h1>
								</div>
								<div class="timezone">
									<div class="displaySection">
										<i class="fa fa-clock-o"></i>
										<span ng-bind="mentee.time_zone_str" class="ng-binding">Bangkok (+07:00)</span>
										<span class="editorText editSection">
											<i class="icon-edit"></i>
										</span>
									</div>
									<div class="formSection ng-hide" ng-show="isEditingSection(&quot;time_zone&quot;);">
										<select ng-model="mentee.time_zone" name="user[time_zone]" id="user_time_zone" class="ng-pristine ng-untouched ng-valid"><option value="Hawaii">(GMT-10:00) Hawaii</option>
											<option value="Bangkok">(GMT+07:00) Bangkok</option>
											<option value="Hanoi">(GMT+07:00) Hanoi</option>
											<option value="Jakarta">(GMT+07:00) Jakarta</option>
											<option value="Krasnoyarsk">(GMT+07:00) Krasnoyarsk</option>
										</select>
										<span class="editorText">
											<div class="btn saveButton btn-primary">Save</div>
										</span>
										<span class="editorText">
											<div class="btn btn-link cancelButton">Cancel</div>
										</span>
									</div>
								</div>
								<div class="needCategories">
									<div class="needCatTitle">
										<i class="fa fa-tags"></i>
										Topic I need help with:
										<span class="editorText"><i class="icon-edit"></i></span>
										<span class="formSection ng-hide">
											<span class="editorText">
												<div class="btn saveButton btn-primary">Save</div>
											</span>
											<span class="editorText">
												<div class="btn btn-link cancelButton">Cancel</div>
											</span>
										</span>
									</div>
								</div>
								<div class="row-fluid">
									<div class="span10 needCatContent">
										<span class="badge customizeBadge ng-binding ng-scope">JavaScript</span>
									</div>
									<div class="formSection ng-hide">
										<div class="control-group text tagInput ng-scope">
											<div class="controls">
												<tags-input min-length="1" placeholder="Search Categories..." class="ng-pristine ng-untouched ng-valid ng-isolate-scope ng-valid-max-tags ng-valid-min-tags ng-valid-leftover-text">
													<div class="host" tabindex="-1">
														<div class="tags">
															<ul class="tag-list">
																<li class="tag-item ng-scope">
																	<ti-tag-item data="tag" class="ng-isolate-scope skrollable skrollable-between">
																		<ng-include src="$$template" class="ng-scope">
																			<span ng-bind="$getDisplayText()" class="ng-binding ng-scope">JavaScript</span>
																			<a class="remove-button ng-binding ng-scope">×</a>
																		</ng-include>
																	</ti-tag-item></li>
															</ul>
															<input class="input ng-pristine ng-untouched ng-valid" autocomplete="off"  type="text" placeholder="Search Categories..." style="width: 138px;">
															<span class="input" style="visibility: hidden; width: auto; white-space: pre; display: none;">Search Categories...</span>
														</div>
														<auto-complete min-length="1" class="ng-scope ng-isolate-scope">

														</auto-complete>
													</div>
												</tags-input>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="menuPart skrollable skrollable-before" data-50-top="position:fixed;" data-bottom-top="position:relative;" data-emit-events="" style="position: relative; top: auto; box-shadow: none;">
			<div class="customizeContainer">
				<div class="menuTab active">
					<a class="menuLink tabQuestion">
						Overview
					</a>
				</div>
				<span class="aboutMe red">* Your profile is not public and is only visible to mentors on Codementor</span>
			</div>
		</div>
		<div class="contentPart secondPart skrollable skrollable-before" data-104-top="padding-top:55px;" data-105-top="padding-top:0px;" data-emit-events="" style="padding-top: 0px;">
			<div class="customizeContainer">
				<div class="row-fluid">
					<div class="span8">
						<div id="overview">
							<div class="block">
								<h2 class="subTitle">
									About Me
									<span class="editSection editorText">
										<i class="icon-edit"></i>
									</span>
									<span class="formSection ng-hide">
										<span class="editorText">
											<div class="btn saveButton btn-primary">Save</div>
										</span>
										<span class="editorText">
											<div class="btn btn-link cancelButton">Cancel</div>
										</span>
									</span>
								</h2>
								<div class="blockDecoration whyUse">
									<ul class="editorText"></ul>
									<ul class="use_text ng-hide">
										<li class="ng-scope">
											<label for="why_use_0" class="ng-binding">
												<input id="why_use_0"type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'm working on a side project
											</label>
										</li>
										<li class="ng-scope">
											<label for="why_use_1" class="ng-binding">
												<input id="why_use_1"  type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'm building a startup
											</label>
										</li>
										<li class="ng-scope">
											<label for="why_use_2" class="ng-binding">
												<input id="why_use_2" type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'm a freelance developer
											</label>
										</li>
										<li class="ng-scope">
											<label for="why_use_3" class="ng-binding">
												<input id="why_use_3"  type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'm a student
											</label>
										</li>
										<li class="ng-scope">
											<label for="why_use_4" class="ng-binding">
												<input id="why_use_4" type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'd like to find a job as a developer
											</label>
										</li>
										<li class="ng-scope">
											<label for="why_use_5" class="ng-binding">
												<input id="why_use_5"  type="checkbox" class="ng-pristine ng-untouched ng-valid">
												I'm working as a full-time developer at a company
											</label>
										</li>
										<li class="other">
											Other:
											<input style="display:inline;" type="text" class="ng-pristine ng-untouched ng-valid">
										</li>
									</ul>
									<ul class="use_text">
										<li class="ng-binding ng-scope">I'm a student</li>
									</ul>
								</div>
							</div>
							<div class="block">
								<h2 class="subTitle">
									Requests
								</h2>
								<div class="blockDecoration">
									<div class="request">
										<div class="requestDetail">
											<h4 class="qTitle">
												<a href="/questions/7659868537">
													html ruby
												</a>
											</h4>
											<p class="qBody">

											</p>
										</div>
										<div class="requestSign solved">
											<div class="signText">
												Solved
											</div>
										</div>
										<a class="tags" href="/html_css-experts">
											HTML/CSS
										</a>
										<a class="tags" href="/html-experts">
											Html
										</a>
										<a class="tags" href="/ruby-experts">
											Ruby
										</a>
									</div>
									<div class="request">
										<div class="requestDetail">
											<h4 class="qTitle">
												<a href="/questions/8560876903">
													nodejs, socket-io
												</a>
											</h4>
											<p class="qBody">

											</p>
										</div>
										<div class="requestSign solved">
											<div class="signText">
												Solved
											</div>
										</div>
										<a class="tags" href="/nodejs-experts">
											Node.js
										</a>
										<a class="tags" href="/socket-io-experts">
											Socket io
										</a>
										<a class="tags" href="/nodejs-dup-experts">
											Nodejs
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>