<footer class="footer_area">

    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <p>© 2015 FUNIX. All rights reserved</p>
                </div>
                <div class="col-sm-8">
                    <nav class="footer_menu">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="mentor.html">Mentor</a></li>
                            <li><a href="http://cyberlms.fpt.edu.vn/">Course</a></li>
                            <li><a href="about.html">About</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php
$this->user()->getMentor();

$mytoken = '';
if ($this->user()->getIdentity()) {
$mytoken = strtotime($this->user()->getUser($this->user()->getIdentity())->getCreatedDateTime()); ?>

    <?php if($this->user()->getUser($this->user()->getIdentity())->getRole() != \User\Model\User::ROLE_CALLCENTER){ ?>
<div id="chat_boxid" class="chat_box">
    <div class="chat_head">Trợ giúp</div>
    <div class="chat_body"><?php
        foreach ($this->user()->getCallCenter() as $callcenter) { ?>
            <?php
                if ($callcenter != $this->user()->getUser($this->user()->getIdentity())->getUsername()) {
                    ?>
                    <div id="chat_list">
                        <!--                        <div id="chat_avatar">-->
                        <!--                            <img src="https://www.gravatar.com/avatar/590ffe5b72621194f8759180d6d49440?d=mm&s=200"">-->
                        <!--                        </div>-->
                        <div class="user" style="cursor:pointer;" onclick="popupchat('<?=$callcenter ?>')"><?=$callcenter ?></div>
                    </div>
                    <?php
                }
        } ?>
    </div>
</div>
<?php } ?>

<div id="chat-area"></div>
<?php if($this->user()->getUser($this->user()->getIdentity())->getRole() == \User\Model\User::ROLE_CALLCENTER){ ?>
<div id="chat_boxmentor" class="chat_box">
    <div class="chat_head">Mentor</div>
    <div class="chat_body"><?php
        foreach ($this->user()->getMentor() as $sub=>$mentor) { ?>
            <h4 class="subject_mentor"><?=$sub?></h4>
            <?php
            foreach ($mentor as $name) {
                if ($name != $this->user()->getUser($this->user()->getIdentity())->getUsername()) {
                    ?>
                    <div id="chat_list">
                        <div class="user" style="cursor:pointer;" onclick="popupchat('<?=$name ?>')"><?=$name ?></div>
                    </div>
                    <?php
                }
            }
        } ?>
    </div>
</div>

<div class="mentorlist" style="display: none">
    <div class="chat_head">Mentor</div>
    <div class="chat_body" style="height: 248px;"><?php
        foreach ($this->user()->getMentor() as $subjectname => $mentor) { ?>
            <h4 class="subject_mentor"><?= $subjectname ?></h4>
            <?php
            foreach ($mentor as $name) {
                if ($name != $this->user()->getUser($this->user()->getIdentity())->getUsername()) {
                    ?>
                    <div id="chat_list">
                        <div class="user <?=$name?>" style="cursor:pointer;" onclick="updateuserchat(this,'<?=$name ?>')"><?=$name ?></div>
                    </div>
                    <?php
                }
            }
        } ?>
    </div>
</div>
<?php }
} ?>