<?php
$this->headScript()->appendFile('/js/typeahead.bundle.js');
$this->headScript()->appendFile('/js/bootstrap-tagsinput.min.js');
$this->headScript()->appendFile('/min?f=/js/jquery.redirect.js');
$this->headLink()->prependStylesheet('/css/bootstrap-tagsinput.css');
$this->headLink()->prependStylesheet('/css/home/get_help_now.css');
$this->headLink()->prependStylesheet('/css/home/directory_new_for_clients.css');
$this->headScript()->appendFile('/min?f=/tp/v1/js/home/search/index.js');
$form = $this->form;
$subjects = $this->subjects;
$expertsubPaginator = $this->expert;
?>

<div class="alerts">
    <!-- ngRepeat: alert in Alert.alerts -->
</div>
<div class="directory">
    <div class="resultBlock">
        <div class="customizeContainer">
            <div class="switchBlock">
                <div class="row-fluid">
                    <div class="span9">
                        <h2 class="sub-title">
                            Nhận sự giúp đỡ trực tiếp từ các chuyên gia
                        </h2>
                        <hr class="bg-splitter">
                        <div class="request-section-wrapper">
                            <div class="request-section skrollable skrollable-before">
                                <div class="request-info-wrapper">
                                    <img class="request-icon" src="/images/icon-request.png">
                                    <!-- ngIf: !questionTitle -->
                                    <h2 class="request-title" ng-if="questionTitle">
                                        <?=$this->searchContent?>
                                    </h2><!-- end ngIf: questionTitle -->
                                    <hr ng-hide="requestSent">
                                    <div class="row-fluid request-info" ng-hide="requestSent">
                                        <div class="span7 request-categories">
                                            <?php
                                            foreach($subjects as $s){
                                                ?>
                                                <div class="cate">
                                                    <?=ucfirst($s->getName())?>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                        </div>
<!--                                        <div class="span5 text-right">-->
<!--                                            <button class="btn-post-request btn btn-red">-->
<!--                                                Tiếp tục cần sự trợ giúp của Mentor-->
<!--                                                <i class="icon-chevron-down" style="margin-left: 5px;"></i>-->
<!--                                            </button>-->
<!--                                        </div>-->
                                    </div>
                                    <!-- ngIf: requestSent -->
                                </div>
                                <form class="request-form ng-hide">
                                    <img class="request-icon" src="/images/icon-request.png">
                                    <h2 class="form-title">
                                        Please provide more details about your request
                                    </h2>
                                    <div class="form-body">
                                        <label class="lable-title">
                                            What do you need help with?
                                        </label>
                                        <?=$this->formelement($form->get('search')->setValue($this->searchContent))?>
                                        <?=$this->formelement($form->get('searchDetail'))?>
                                        <div class="control-group text required question_category_names tagInput">
                                            <div class="controls">
                                                <input name="subject" class="input" placeholder="Add tags (e.g. Javascript)" autocomplete="off" style="width: 170px;">
<!--                                                <div class="bootstrap-tagsinput">-->
<!--                                                    <input data-role="tagsinput" class="input ng-pristine ng-valid ng-touched" type="text" name="subject" maxlength="255"  placeholder="Tên môn học" id="subject" value="" class="ui-autocomplete-input" autocomplete="off">-->
<!--                                                </div>-->
                                            </div>
                                        </div>
                                        <label class="label-budget">
                                            What's your maximum hourly budget?
                                        </label>
                                        <div class="budget-buttons" data-toggle-name="radius_options">
                                            <button class="btn" data-toggle="button" value="5"type="button">
                                                $20
                                            </button>
                                            <button class="btn" data-toggle="button" value="10"type="button">
                                                $40
                                            </button>
                                        </div>
                                        <input type="hidden" name="radius_options" value="5">
                                        <div class="row-fluid account-info">
                                            <div class="span6">
                                                <label class="label-email">
                                                    Email:
                                                    <small style="font-weight: 400;">
                                                        ( Already have an account?
                                                        <a href="javascript:showPassword();">
                                                            Sign In
                                                        </a>
                                                        )
                                                    </small>
                                                    <small style="font-weight: 400;" class="ng-hide">
                                                        ( Don't have an account?
                                                        <a href="#">
                                                            Sign Up
                                                        </a>
                                                        )
                                                    </small>
                                                </label>
                                                <?=$this->formelement($form->get('email')->setAttributes([
                                                    'class' =>  'input-email',
                                                    'placeholder'   =>  'Email',
                                                ]))?>
                                            </div>
                                            <div class="span6">
                                                <div class="password-input ng-hide">
                                                    <label class="label-password">
                                                        Password:
                                                    </label>
                                                    <?=$this->formelement($form->get('password')->setAttributes([
                                                        'class' => 'input-password',
                                                        'placeholder'   =>  'Mật khẩu',
                                                        'autocomplete'  =>  'off',
                                                    ]))?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row-fluid">
                                        <div class="span7 text-left">
                                            <div class="errorMsg ng-binding">

                                            </div>
                                        </div>
                                        <div class="span5 text-right">
                                            <div class="btn cancel">
                                                Cancel
                                            </div>
                                            <div id="submit" class="btn btn-red">
                                                Get Help Now
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-fluid logging-requesting ng-hide">
                                        <div class="span12 text-right muted">
                                            Loading ...
                                            <i class="icon-spin icon-refresh"></i>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="expert-list" ng-hide="loaded" style="margin-top: 204px;">
                            <?php
                            if($expertsubPaginator->getCurrentModels()){
                            foreach($expertsubPaginator->getCurrentModels() as $expertsub){
                                /** @var \User\Model\User $mentor */
                                $mentor = $expertsub->getOption('user');
                                $subs = $expertsub->getOption('subject');
                                ?>
                            <div class="mentorModule">
                                <div class="row-fluid mentor-item-row">
                                    <div class="span3 text-center mentor-info">
                                        <div>
                                            <img class="img-circle headImg" src="<?=\Home\Service\Uri::getViewPath($mentor)?>">
                                        </div>
                                        <div class="rate">
<!--                                            <strong>$30.00</strong>-->
<!--                                            <small>/15min</small>-->
                                        </div>
                                        <?php if(!$this->user()->getIdentity) {
                                        ?>
                                            <a class="btn btn-success messageBtn" data-target="#signup-modal" data-toggle="modal" role="button" href="#">
                                                Gửi tin nhắn
                                            </a>
                                        <?php
                                        }elseif($this->user()->getIdentity && $this->user()->getUser()->getRole() == \User\Model\User::ROLE_MEMBER){?>
                                        <a class="btn btn-success messageBtn" href="#">
                                            Gửi tin nhắn
                                        </a>
                                    <?php }?>
                                    </div>
                                    <div class="span9 mentor-details">
                                        <a class="name" href="/consultwithmike" target="consultwithmike">
                                            <?=$mentor->getUserName()?>
                                        </a>
<!--                                        <span class="ratingNum">4.9</span>-->
                                        <div class="rating">
<!--                                            <span> ★ </span>  <span> ★ </span>  <span> ★ </span>  <span> ★ </span>  <span> ★ </span>-->
                                        </div>
                                        <sup class="online">
                                            <?php
                                            if($mentor->getStatus() == \User\Model\User::STATUS_ONLINE){
                                                echo '<span class="online"><i class="icon-circle"></i>ONLINE</span>';
                                            }
                                            ?>
                                        </sup>
<!--                                        <div class="headLine">-->
<!--                                            <small>-->
<!--                                                Enterprise application developer with 15 years of experience in the industry.-->
<!--                                            </small>-->
<!--                                        </div>-->
                                        <div class="about">
                                            <?=$mentor->getDescription()?>
                                        </div>
                                        <div class="expertise">
                                            <?php foreach($subs as $sid=>$sname){?>
                                            <div class="badge customizeBadge">
                                                <a class="removeDec" href="/experts/index/view?id=<?=$sid?>">
                                                    <?=$sname?>
                                                </a>
                                            </div>
                                            <?php }?>
                                        </div>
                                        <div class="hirable">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php }} ?>
                        </div>
                        <div class="signupModule">
                            <div class="row-fluid">
                                <div class="span12">
                                    <h3 class="signupTitle">
                                    </h3>
                                    <br>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="span3">
                        <h2 class="sub-title">
                        </h2>
                        <hr class="bg-splitter">
                        <div class="reviews" ng-hide="loaded">
                            <div class="review">
                                <div class="writer">
                                    <span class="img-circle headImg ng-isolate-scope" img-src="" name="Leonard Mbah Acha">
                                        <img ng-hide="!!userShortName" class="img-circle avatar ng-hide"  src="">
                                    </span>
                                    <span class="name"></span>
                                </div>
                                <div class="content">
                                    <p>

                                    </p>
                                    <span class="rating"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal hide fade" id="signup-modal" menu-sign-up-form="" role="dialog" tabindex="-1">
    <div class="modal-header">
        <h3 class="ng-binding">
            Đăng kí và nhận sự trợ giúp luôn
        </h3>
    </div>
    <div class="modal-body" style="overflow: hidden;">

        <div class="extra-info alter alert-success ng-binding ng-hide" ng-show="sf.extraInfo">

        </div>
        <div class="row-fluid">
            <div class="span5">
                <div class="leftBlock">
                    <p class="signup-txt">
                        <b>
                            Funix
                        </b>
                        <!--                        your instant 1:1 expert mentor helping you in real time.-->
                    </p>
                    <div class="muted">
                        Bạn đã có tài khoản?
                        <a href="/user/signin">Đăng nhập</a>
                    </div>
                    <div class="applyMentor">
                        <a class="side_link" href="/experts/index/apply"">Bạn muốn trở thành mentor?</a>
                    </div>
                </div>
            </div>
            <div class="span7">
                <div class="menuSignUpForm">
                    <div class="sign_up_form">
                        <input label="false" class="string email required bigform input_email" type="email" pattern=".*" placeholder="Địa chỉ email" name="email" id="user_email">
                        <div class="action clearfix">
                            <button type="submit" id="signupemail" name="commit" class="btn btn-primary pull-right">Đăng kí</button>
                            <div class="muted pull-right termOfService">
                                Bằng việc click vào nút đăng kí, tức là bạn đã đồng ý với các
                                <a href="#" target="_blank">điểu khoản</a>
                                của chúng tôi
                            </div>
                        </div>
                        <div id="errorModal"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>