<?php
$this->headLink()->prependStylesheet('/css/bootstrap.min.css');
$this->headLink()->prependStylesheet('/css/wizard/bootstrap-wizard.min.css');
$this->headScript()->appendFile('/js/wizard/jquery.bootstrap.wizard.min.js');
$this->headScript ()->appendFile( '/js/funix/loadData.js' );
$this->headScript()->appendFile('/min/f=/tp/v1/js/expert/index/apply.js');


function renderElementForm($view,$form,$element){
    if(!$element->getAttribute('id')) {
        $element->setAttribute('id', $element->getName());
    }

    $inputFilter = null;
    if($form->getInputFilter()->has($element->getName())) {
        /* @var $inputFilter Zend\InputFilter\Input */
        $inputFilter = $form->getInputFilter()->get($element->getName());
    }

    if($element instanceof \Zend\Form\Element\Hidden){
        echo $view->formElement($element);
        return;
    }
    $boundaryAttr = [
        'class' => 'form-group'
    ];
    if($element->getOption('boundaryElement') && is_array($element->getOption('boundaryElement'))){
        foreach ($element->getOption('boundaryElement') as $attr=>$value){
            if($attr == 'class'){
                $boundaryAttr['class'] .= ' '.$value;
            } else {
                $boundaryAttr[$attr] = $value;
            }
        }
    }
    $boundaryElement = '<div ';
    foreach ($boundaryAttr as $attr=>$value){
        $boundaryElement .= $attr.'="'.$value.'" ';
    }
    $boundaryElement .= '/>';
    echo $boundaryElement;

    $labelSpan = '';
    $labelClass = '';
    if($element->getLabel()) {
        if($inputFilter && $inputFilter->isRequired()) {
            $labelClass = " required";
            $labelSpan = " <span class='required'>*</span> ";
        }
    }

    // set column layout
    $labelCol = "span2";
    $elementCol = "span3";
    if($element->getOption('layout') == 'fluid') {
        $labelCol = 'span2';
        $elementCol = 'span3';
    }

    echo "<label class='$labelCol control-label$labelClass'>". $element->getLabel() . $labelSpan .'</label>';
    echo "<div class='$elementCol'>";

    $class = $element->getAttribute('class');
    if(in_array($element->getAttribute('type'), ['text', 'select', 'password', 'select', 'date'])) {
        $element->setAttribute('class', $class ? $class . ' form-control' : 'form-control');
    }

    // render element based on type
    if($element instanceof \Zend\Form\Element\Radio) {
        if(is_array($element->getOption('value_options'))) {
            foreach($element->getOption('value_options') as $key => $label) {
                echo '<label class="radio radio-inline">';
                $checked = ($key == $element->getValue()) ? ' checked=checked ' : '';
                echo "<input$checked type='radio' value='". $key ."' name='". $element->getName() ."'/>". $label;
                echo '</label>';
            }
        }
        if($element->getValueOptions() && !is_array($element->getOption('value_options'))) {
            foreach($element->getValueOptions() as $key => $label) {
                echo '<label class="radio radio-inline">';
                $checked = ($key == $element->getValue()) ? ' checked=checked ' : '';
                echo "<input$checked type='radio' value='". $key ."' name='". $element->getName() ."'/>". $label;
                echo '</label>';
            }
        }
    } else if ($element->getOption('leftIcon') || $element->getOption('rightIcon')) {
        echo '<div class="input-group">';
        if($element->getOption('leftIcon')) {
            echo '<span class="input-group-addon"><i class="'. $element->getOption('leftIcon') .'"></i></span>';
        }
        echo $view->formElement($element);
        if($element->getOption('rightIcon')) {
            echo '<span class="input-group-addon"><i class="'. $element->getOption('rightIcon') .'"></i></span>';
        }
        echo '</div>';
    } else {
        echo $view->formElement($element);
    }
    if($element->getOption('descriptions') && is_array($element->getOption('descriptions'))){
        echo '<ul class="parsley-description-list">';
        foreach ($element->getOption('descriptions') as $description){
            echo '<li>'.$description.'</li>';
        }
        echo '</ul>';
    }
    // render error messages
    if(is_array($element->getMessages()) && count($element->getMessages())) {
        echo '<ul class="parsley-error-list">';
        foreach($element->getMessages() as $validatorType => $message) {
            echo '<li>'. $message .'</li>';
        }
        echo '</ul>';
    }

    echo '</div>';
    echo '</div>';
}
?>
<div id="inner-body">
    <div class="customizeContainer">
        <center>
            <div class="module">
                <h1 class="title">
                    Đăng kí trở thành chuyên gia
                </h1>
                <p class="subtitle">
                    Mặc nhiên khi đăng kí, bạn đã đồng ý với các
                    <a class="learn-more" href="#" ng-click="learnMore()">
                        chính sách
                    </a>
                    giành cho Chuyên gia của Funix.
                </p>
                <div class="main-content">
                    <div class="widget">
                        <div class="widget-header">
                            <h3><i class="fa fa-magic"></i>Đăng kí trở thành chuyên gia</h3>
                        </div>
                        <div class="widget-content">
                            <div id="rootwizard" class="col-md-12">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <div class="container">
                                            <ul>
                                                <li><a href="#tab1" data-toggle="tab">Thông tin cơ bản</a></li>
                                                <li><a href="#tab2" data-toggle="tab">Khung thời gian và môn học</a></li>
                                                <li><a href="#tab3" data-toggle="tab">Third</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-content">
                                    <div class="tab-pane" id="tab1">
                                        <?php
                                        $form = $this->form;
                                        $inputFilter = $form->getInputFilter();
                                        $form->prepare();
                                        echo $this->form()->openTag($form);
                                        echo '<p>Các thông tin cơ bản của mentor<br><em><small>Các trường có dấu * là bắt buộc</small></em></p>';
                                        echo '<div class="row">';
                                        echo '<div class=col-md-3>';
                                        echo renderElementForm($this,$form,$form->get('fullname'));
                                        echo renderElementForm($this,$form,$form->get('email'));
                                        echo renderElementForm($this,$form,$form->get('skype'));
                                        echo renderElementForm($this,$form,$form->get('mobile'));
                                        echo renderElementForm($this,$form,$form->get('social'));
                                        echo renderElementForm($this,$form,$form->get('isTeaching'));
                                        echo renderElementForm($this,$form,$form->get('description'));
                                        echo renderElementForm($this,$form,$form->get('cityId'));
                                        echo renderElementForm($this,$form,$form->get('districtId'));
                                        echo renderElementForm($this,$form,$form->get('address'));
                                        echo '</div></div>';
                                        echo $this->form()->closeTag();
                                        ?>
                                    </div>
                                    <div class="tab-pane" id="tab2">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group span4">
                                                    <label for="email">Anh/Chị hãy nhập khung thời gian có thể online</label>
                                                    <div class="checkbox span4">
                                                        <label><input type="checkbox" value="1">Thứ hai: 8:00 pm - 11:00 pm</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="tab3">
                                        3
                                    </div>
                                    <ul class="pager wizard">
                                        <li class="previous first" style="display:none;"><a href="#">First</a></li>
                                        <li class="previous"><a href="#">Previous</a></li>
                                        <li class="next last" style="display:none;"><a href="#">Last</a></li>
                                        <li class="next"><a href="#">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </center>
    </div>
</div>

<style>
    .main-content {
        padding-bottom: 30px;
    }
    .widget {
        border-color: #2c98c6;
        border-width: 1px;
        border-style: solid;
        margin-bottom: 20px;
        background-color: #f9f9f9;
    }
    .widget .widget-header {
        background-color: #1e6887;
        border-bottom-color: #195872;
        color: #fff;
        padding: 0 10px;
        height: 35px;
        border-bottom-width: 1px;
        border-bottom-style: solid;
    }
    .widget .widget-content {
        padding: 20px 10px;
    }
    .wizard {
        position: relative;
        overflow: hidden;
        background-color: #f9f9f9;
    }
    .wizard ul {
        width: 4000px;
        padding: 0;
        margin: 0;
        list-style: none outside none;
    }
    .wizard ul li.active {
        color: #fff;
        background: #296EAA;
    }
    .wizard ul li:first-child {
        padding-left: 20px;
    }
    .wizard ul li {
        position: relative;
        float: left;
        height: 46px;
        padding: 0 20px 0 30px;
        margin: 0;
        font-size: 16px;
        line-height: 46px;
        color: #a5a5a5;
        cursor: default;
        background: #f2f2f2;
    }
    .wizard ul li .badge.badge-info {
        background-color: #1f5381;
    }
    .wizard ul li .badge {
        position: relative;
        top: -2px;
        margin-right: 8px;
        padding: 4px 7px;
    }
    .badge {
        font-weight: 400;
    }
    .badge {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        background-color: #777;
        border-radius: 10px;
    }
    .wizard ul li .chevron {
        position: absolute;
        top: -24px;
        right: -14px;
        z-index: 1;
        display: block;
        border: 48px solid transparent;
        border-right: 0;
        border-left: 24px solid #fff;
    }
    .row {
        margin-right: -15px;
        margin-left: -15px;
    }
</style>