<?php
$this->headLink()->prependStylesheet('/css/home/directory_new_for_clients.css');
$this->headScript()->appendFile('/tp/v1/js/expert/index/index.js');
$this->headLink()->prependStylesheet('/tp/v1/css/expert/view.css');
$subjectsCategory = $this->subjects;
?>
<div class="topBlock">
    <div class="customizeContainer">

        <div class="row-fluid">
            <?php include(TEMPLATES_PATH.'\html\expert.html')?>
            <?php if(!$this->user()->getIdentity()){?>
                <a class="actionLink" data-target="#signup-modal" data-toggle="modal" role="button">
                    Nhận sự giúp đỡ luôn
                </a>
            <?php }?>
        </div>
    </div>
</div>
<div class="breadcrumb">
    <div class="customizeContainer">
        <div class="row-fluid">
            <div class="span12">
                <div :xmlns:v="http://rdf.data-vocabulary.org/#" class="innerBreadcrumb">
<span ng-hide="loaded" typeof="v:Breadcrumb">
<span class="lastLink" typeof="v:Breadcrumb">
Expert Mentors
</span>
</span>
                    <!-- ngIf: loaded -->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="searchBlock">
    <div class="customizeContainer">
        <div class="row-fluid">
            <div class="span9">
                <div class="searchBarContent">
                    <div class="bootstrap-tagsinput">
                        <input class="input ng-pristine ng-valid ng-touched" type="text" name="subject" maxlength="255"  placeholder="Tên môn học" id="subject" value="" class="ui-autocomplete-input" autocomplete="off">
                    </div>
                </div>
                <div class="searchButton" ng-click="searchAndRedirect()">
                    Search
                </div>
            </div>
        </div>
    </div>
</div>
<div class="resultBlock">
    <div class="customizeContainer">
        <div class="switchBlock">
            <?php
            $countCate = 0;
            foreach($subjectsCategory as $category=>$subjects){
                $countCate++;
                if($countCate == 1){
                    ?>
                    <div class="row-fluid">
                    <div class="span4">
                        <div class="topicBlock">
                            <a class="link" href="/experts/index/list?id=<?=explode('-',$category)[0]?>">
                                <center>
                                    <img alt="<?=explode('-',$category)[1]?>" class="imgBlock" src="/images/topic/web-programming.png">
                                    <span class="titleBlock"><?=explode('-',$category)[1]?></span>
                                </center>
                            </a>
                            <div class="moreLink">
                                <?php
                                $count = 0;
                                $total = count($subjects);
                                foreach($subjects as $subject){
                                    $count++;
                                    $total--;
                                    if($count == 1) {
                                        if (count($subjects) > 1 && $total>0) {
                                            ?>
                                            <div class="row-fluid">
                                            <div class="span6">
                                                <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                    <?=$subject['name']?>
                                                </a>
                                            </div>
                                            <?php
                                        }elseif($total == 0){
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }else{
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                    }elseif($count==2){
                                        $count = 0;
                                        ?>
                                        <div class="span6">
                                            <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                            <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                <?= $subject['name'] ?>
                                            </a>
                                        </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <?php
                }elseif($countCate == 3){
                    $countCate = 0;
                    ?>
                    <div class="span4">
                        <div class="topicBlock">
                            <a class="link" href="/experts/index/list?id=<?=explode('-',$category)[0]?>">
                                <center>
                                    <img alt="<?=explode('-',$category)[1]?>" class="imgBlock" src="/images/topic/web-programming.png">
                                    <span class="titleBlock"><?=explode('-',$category)[1]?></span>
                                </center>
                            </a>
                            <div class="moreLink">
                                <?php
                                $count = 0;
                                $total = count($subjects);
                                foreach($subjects as $subject){
                                    $count++;
                                    $total--;
                                    if($count == 1) {
                                        if (count($subjects) > 1 && $total>0) {
                                            ?>
                                            <div class="row-fluid">
                                            <div class="span6">
                                                <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                    <?=$subject['name']?>
                                                </a>
                                            </div>
                                            <?php
                                        }elseif($total == 0){
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }else{
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                    }elseif($count==2){
                                        $count = 0;
                                        ?>
                                        <div class="span6">
                                            <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                            <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                <?= $subject['name'] ?>
                                            </a>
                                        </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    </div>
                    <?php
                }else{
                    ?>
                    <div class="span4">
                        <div class="topicBlock">
                            <a class="link" href="/experts/index/list?id=<?=explode('-',$category)[0]?>">
                                <center>
                                    <img alt="<?=explode('-',$category)[1]?>" class="imgBlock" src="/images/topic/web-programming.png">
                                    <span class="titleBlock"><?=explode('-',$category)[1]?></span>
                                </center>
                            </a>
                            <div class="moreLink">
                                <?php
                                $count = 0;
                                $total = count($subjects);
                                foreach($subjects as $subject){
                                    $count++;
                                    $total--;
                                    if($count == 1) {
                                        if (count($subjects) > 1 && $total>0) {
                                            ?>
                                            <div class="row-fluid">
                                            <div class="span6">
                                                <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                    <?=$subject['name']?>
                                                </a>
                                            </div>
                                            <?php
                                        }elseif($total == 0){
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }else{
                                            ?>
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                                    <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                        <?=$subject['name']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                    }elseif($count==2){
                                        $count = 0;
                                        ?>
                                        <div class="span6">
                                            <img class="catImg" src="/images/experts/ruby-expert-help.png">
                                            <a class="catLink" href="/experts/index/view?id=<?=$subject['id'] ?>">
                                                <?= $subject['name'] ?>
                                            </a>
                                        </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            <?php } ?>
        </div>
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal hide fade" id="signup-modal" menu-sign-up-form="" role="dialog" tabindex="-1">
    <div class="modal-header">
        <h3 class="ng-binding">
            Đăng kí và nhận sự trợ giúp luôn
        </h3>
    </div>
    <div class="modal-body" style="overflow: hidden;">

        <div class="extra-info alter alert-success ng-binding ng-hide" ng-show="sf.extraInfo">

        </div>
        <div class="row-fluid">
            <div class="span5">
                <div class="leftBlock">
                    <p class="signup-txt">
                        <b>
                            Funix
                        </b>
<!--                        your instant 1:1 expert mentor helping you in real time.-->
                    </p>
                    <div class="muted">
                        Bạn đã có tài khoản?
                        <a href="/user/signin">Đăng nhập</a>
                    </div>
                    <div class="applyMentor">
                        <a class="side_link" href="/experts/index/apply"">Bạn muốn trở thành mentor?</a>
                    </div>
                </div>
            </div>
            <div class="span7">
                <div class="menuSignUpForm">
                    <div class="sign_up_form">
                        <input label="false" class="string email required bigform input_email" type="email" pattern=".*" placeholder="Địa chỉ email" name="email" id="user_email">
                        <div class="action clearfix">
                            <button type="submit" id="signupemail" name="commit" class="btn btn-primary pull-right">Đăng kí</button>
                            <div class="muted pull-right termOfService">
                                Bằng việc click vào nút đăng kí, tức là bạn đã đồng ý với các
                                <a href="#" target="_blank">điểu khoản</a>
                                của chúng tôi
                            </div>
                        </div>
                        <div id="errorModal"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" name="subjectId" id="subjectId" value="">